title: "Sophocles' Ajax: a Commentary on Commentaries"
description: "How does a classical hero die in the digital age? Using Sophocles’ Ajax to create a commentary on commentaries."
show_downloads: false
theme: jekyll-theme-minimal
